spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: resumehero
indeed-listing-scraper:
  searches:
  - query: eb21
    location:
    country: sg
    jobtype:
  - query: java
    location:
    country: us
    jobtype: fulltime