spring:
  datasource:
    url: jdbc:mysql://localhost/resumehero
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
indeed-listing-scraper:
  searches:
  - q: java
    l:
    jt: fulltime
  - q: php
    l:
    jt: fulltime
  - q: ruby
    l:
    jt: fulltime
