spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: resumehero
indeed-listing-scraper:
  searches:
  - query: java
    location:
    jobtype: fulltime
  - query: php
    location:
    jobtype: fulltime
  - query: ruby
    location:
    jobtype: fulltime
