spring:
  datasource:
    url: jdbc:mysql://localhost/resumehero
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
indeed-listing-scraper:
  searches:
  - query: java
    location:
    jobtype: fulltime
  - query: php
    location:
    jobtype: fulltime
  - query: ruby
    location:
    jobtype: fulltime
